[colors]
background = "#201f23FF"
text_primary = "#e5e1e6FF"
text_muted = "#c8c5d0FF"
accent_primary = "#c5c0fdFF"
accent_secondary = "#c7c3deFF"
warning = "#f2b3e1FF"
error = "#ffb4abFF"
insert_hint = "#f2b3e180"
backdrop = "#47464fFF"

[colors.border]
focused = "#c5c0fdFF"
unfocused = "#47464fFF"
scratchpad_focused = "#f2b3e1FF"
scratchpad_unfocused = "#481c41FF"
outer = "#141316FF"

[colors.overview]
background_tint = "#14131688"
badge = "#c5c0fdFF"
workspace_background = "#141316FF"
