[colors]
background = "#14141eFF"
text_primary = "#e4ded2FF"
text_muted = "#f2eadfFF"
accent_primary = "#bb3535FF"
accent_secondary = "#8baa82FF"
warning = "#9a7398FF"
error = "#c25b5bFF"
insert_hint = "#9a739880"
backdrop = "#14141eFF"

[colors.border]
focused = "#bb3535FF"
unfocused = "#14141eFF"
scratchpad_focused = "#9a7398FF"
scratchpad_unfocused = "#3a2039FF"
outer = "#0a0a12FF"

[colors.overview]
background_tint = "#0a0a1288"
badge = "#bb3535FF"
workspace_background = "#0a0a12FF"
