[colors]
background = "#1f1f24FF"
text_primary = "#e4e1e8FF"
text_muted = "#c6c5d2FF"
accent_primary = "#bac3ffFF"
accent_secondary = "#c1c4e4FF"
warning = "#f3b1f0FF"
error = "#ffb4abFF"
insert_hint = "#f3b1f080"
backdrop = "#454650FF"

[colors.border]
focused = "#bac3ffFF"
unfocused = "#454650FF"
scratchpad_focused = "#f3b1f0FF"
scratchpad_unfocused = "#572459FF"
outer = "#131317FF"

[colors.overview]
background_tint = "#13131788"
badge = "#bac3ffFF"
workspace_background = "#131317FF"
